### ISSUE TITLE
v1.0 Todo

### ISSUE THREAD

**Issue by autotmp** [autotmp/alarmcenter#1]
* [ ] Check for backlight folder/bl_power in backlight widget
* [ ] Add sound
* [ ] Larger SpinnerWidget text
* [ ] Update layout for larger, centered clock

**Comment by autotmp** [comment]
audio link

https://raspberrypi.stackexchange.com/questions/7088/playing-audio-files-with-python
